package com.miqu3iasg.banking.pix.domain;

import com.miqu3iasg.banking.shared.domain.AuditableEntity;
import com.miqu3iasg.banking.pix.exception.InvalidPixStateTransitionException;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Getter
@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(
	name = "pix_charges",
	indexes = {
		@Index(name = "idx_pix_charges_txid", columnList = "txid", unique = true),
		@Index(name = "idx_pix_charges_account_date", columnList = "account_id, created_at"),
		// Partial index on expires_at WHERE status='PENDING' is defined in Flyway V3 migration
		// because JPA @Index does not support partial index predicates.
	}
)
public class PixCharge extends AuditableEntity {

	/**
	 * BACEN spec: txid is 26–35 alphanumeric chars, generated by the PSP.
	 * Unique per charge. Immutable after creation.
	 */
	@Column(unique = true, nullable = false, length = 35, updatable = false)
	private String txid;

	@Column(name = "account_id", nullable = false, updatable = false)
	private UUID accountId;

	@Column(nullable = false, precision = 19, scale = 4)
	private BigDecimal amount;

	@Column(name = "payer_name", length = 200)
	private String payerName;

	@Column(name = "payer_cpf_cnpj", length = 14)
	private String payerCpfCnpj;

	@Column(name = "qr_code", columnDefinition = "TEXT")
	private String qrCode;

	/**
	 * PIX Copia e Cola string. Starts with "00020101" per the EMV QR Code spec.
	 */
	@Column(name = "copy_paste", columnDefinition = "TEXT")
	private String copyPaste;

	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	private PixChargeStatus status;

	@Column(name = "expires_at", nullable = false)
	private Instant expiresAt;

	@Column(name = "paid_at")
	private Instant paidAt;

	public static PixCharge create (
		UUID accountId,
		BigDecimal amount,
		String payerName,
		String payerCpfCnpj,
		String txid,
		int expiresInSeconds
	) {
		if (amount == null || amount.compareTo(BigDecimal.ZERO) <= 0) {
			throw new IllegalArgumentException("PIX charge amount must be positive, got: " + amount);
		}

		if (txid == null || txid.isBlank()) {
			throw new IllegalArgumentException("txid is required and must not be blank");
		}

		if (expiresInSeconds <= 0) {
			throw new IllegalArgumentException("expiresInSeconds must be positive, got: " + expiresInSeconds);
		}

		var charge = new PixCharge();
		charge.txid = txid;
		charge.accountId = accountId;
		charge.amount = amount;
		charge.payerName = payerName;
		charge.payerCpfCnpj = payerCpfCnpj;
		charge.status = PixChargeStatus.PENDING;
		charge.expiresAt = Instant.now().plusSeconds(expiresInSeconds);
		return charge;
	}

	public void enrichWithProviderData (String txid, String qrCode, String copyPaste) {
		this.txid = txid;
		this.qrCode = qrCode;
		this.copyPaste = copyPaste;
	}

	public void markAsPaid (Instant paidAt) {
		requireCanTransitionTo(PixChargeStatus.PAID);
		this.status = PixChargeStatus.PAID;
		this.paidAt = paidAt;
	}

	public void cancel () {
		requireCanTransitionTo(PixChargeStatus.CANCELLED);
		this.status = PixChargeStatus.CANCELLED;
	}

	public void expire () {
		requireCanTransitionTo(PixChargeStatus.EXPIRED);
		this.status = PixChargeStatus.EXPIRED;
	}

	public boolean isExpired () {
		return status == PixChargeStatus.PENDING && Instant.now().isAfter(expiresAt);
	}

	private void requireCanTransitionTo (PixChargeStatus target) {
		if (!this.status.canTransitionTo(target)) {
			throw new InvalidPixStateTransitionException(txid, this.status, target);
		}
	}
}
