server.port=8085
spring.application.name=banking-mvp
spring.profiles.active=dev

# OpenTelemetry Tracing
management.tracing.sampling.probability=1.0
management.observations.key-values.application=banking-mvp
management.observations.key-values.env=dev
