CREATE TABLE pix_charges (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- BACEN spec: txid is 26–35 uppercase alphanumeric chars, generated by the PSP (us)
    -- Immutable after creation — Efí Bank links all events to this txid
    txid            VARCHAR(35) NOT NULL UNIQUE,
    account_id      UUID        NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    amount          NUMERIC(19, 4) NOT NULL CHECK (amount > 0),
    payer_name      VARCHAR(200),
    payer_cpf_cnpj  VARCHAR(14),
    qr_code         TEXT,
    copy_paste      TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expires_at      TIMESTAMPTZ NOT NULL,
    paid_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    version         BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_pix_charges_txid ON pix_charges(txid);
CREATE INDEX idx_pix_charges_account_date ON pix_charges(account_id, created_at DESC);
CREATE INDEX idx_pix_charges_expiration ON pix_charges(expires_at)
    WHERE status = 'PENDING';

CREATE TABLE pix_keys (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id  UUID        NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    type        VARCHAR(10) NOT NULL,

    -- BACEN spec: maximum key value length is 77 characters (longest: email addresses)
    value       VARCHAR(77) NOT NULL,
    status      VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    version     BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_pix_keys_active_value ON pix_keys(value)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_pix_keys_account_status ON pix_keys(account_id, status);

COMMENT ON TABLE pix_charges IS 'PIX immediate charges (cobrança imediata) per BACEN API spec';
COMMENT ON COLUMN pix_charges.txid IS 'BACEN txid: 26–35 uppercase alphanumeric, PSP-generated';
COMMENT ON COLUMN pix_charges.copy_paste IS 'PIX Copia e Cola — starts with 00020101 per EMV QR Code spec';
COMMENT ON COLUMN pix_charges.expires_at IS 'QR Code expiry (TIMESTAMPTZ). Queried by PixExpirationJob via partial index';
COMMENT ON COLUMN pix_charges.paid_at IS 'Timestamp from Efí Bank webhook (horario field). Null until PAID';

COMMENT ON TABLE pix_keys IS 'PIX key registrations per account. Soft-deleted — DELETED rows retained for audit';
COMMENT ON COLUMN pix_keys.value IS 'Normalized key value (lowercase for EMAIL/PHONE). Max 77 chars per BACEN spec';
COMMENT ON INDEX idx_pix_keys_active_value IS 'Enforces key uniqueness among ACTIVE keys only — allows re-registration after deletion';
